import Head from 'next/head'
import Hero from '../components/index_sections/Hero'
import Journey from '../components/index_sections/Journey'
import Projects from '../components/index_sections/Projects'
import Warm from '../components/index_sections/Warm'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sean</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossOrigin="anonymous"/>
      </Head>
      <main>
        <Hero/>
        <Journey/>
        <Projects/>
        <Warm/>
      </main>
    </>
  )
}
